### PR TITLE
move read_config() out of class

### PR DESCRIPTION
**Pull request by laixintao**
I want to make it support OS X, so I need to use this function in MAC class, I have to move it to a
independent package.

Further more, I need refactor more function to make it reusable and testable.

Could you please generously test it on Windows again?

### CODE REVIEW

**Comment by laixintao** [comment]
I am trying to use you qiniu account to test picture uploading, but I get a "bad token error" like below(I can't register to qiniu now so I can only use you account and api key).

Could you plz have a look at my code? in `MarkdownPicPicker.py __main__`

and the error like this:



Thanks

**Comment by kingname** [comment]
In fact, I am developing the OS X version by Swift, instead of Python.

The key problem why I have not develop an OS X version directly is because it is difficult to get the image from pasteboard in OS X by Python, `ImageGrab.grabclipboard()` this method is useless in OS X. 

If you could solve this problem, I will be thankful to you.

**Comment by kingname** [comment]
And for the qiniu token problem, it is reasonable. Anyone can change anything of my account if he had my access key and secret key, so I had changed some characters of these two keys to protect my account. The access key and secret keys in the config.ini is not my real keys. I am so sorry to waste your time by the fake keys....

**Comment by laixintao** [comment]
OK that make sense ^^

I will try to get the picture from pasteboard with python, i will let you know if I success.

**Comment by laixintao** [comment]
Hey I am happily to tell you that I can get the png image from pasteboard.

To Test My Code:
1. make a shortcut
2. run pngpaste.**init** in my branch 

then you can see the image in /tmp

links that I reger:
https://www.v2ex.com/t/249857
https://gist.github.com/Ficapy/8c57998d14c434ab5df3
https://www.zhihu.com/question/19550327

I think using python to finish this work is possible. Let's code in Python, No swift ^ ^

And I am wondering if you could kindly share your secret key with me? ^ ^ because I am not in China now so that I can register another qiniu account.

**Comment by kingname** [comment]
Brilliant!! It could work. 

Could you use pure Python codes or Python's third-part lib to finish the task? Because it will be more friendly if users could run MarkdownPicPicker without installing any other application, and also, it will be more convenient to package MarkdownPicPicker to a binary application for anyone who don't have Python.

**Comment by laixintao** [comment]
I understand you. I will try this and let you know the news ^ ^

**Comment by kingname** [comment]
For upload image to web, I will give you another method.

```
def upload(picture_name):
        picture_file_handler = open(picture_name, 'rb')
        data = {'smfile': picture_file_handler}
        result_json = requests.post('https://sm.ms/api/upload', files=data).content
        try:
            result_dict = json.loads(result_json.decode())
        except Exception as _:
            print('the result of the picture bed is not standard json.' )
            return None
        finally:
            picture_file_handler.close()
        pic_url = result_dict.get('data', {}).get('url', '')
```

call this method to upload image without any token.

**Comment by laixintao** [comment]
Thanks : )

**Comment by kingname** [comment]
hi boy, I have verified your pr, it works well. 

please remove the debug code, and resubmit a pr. I will merge it. thanks.

P.S. : please add a white space after comma. And any .py file should have had a empty line in the tail.

**Comment by kingname** [comment]
please tell me, what is the benefit to move the config.ini to a config folder?

**Comment by laixintao** [comment]
Have a look again :)

Can you explain why should I give py file a empty line? 👍

**Comment by kingname** [comment]
this is a rule in PEP8, just like you should add a white space after a comma.

**Comment by laixintao** [comment]
Get it, thanks 👍

**Comment by laixintao** [comment]
I move config file so that you can reuse the read_config() in mac version.

If read-config() is in main file, you have to write it again. And it is more convenient to read when the file and code are in the same dir.

But actually I usually do this: write config info to a config.py, then you can read it in any platform.

```
import config
xxx = config.xxx
```

I think you want someone that don't know python can also use it, maybe we can use a python dict to store config information in a config.py, what do you think? : )

**Comment by kingname** [comment]
If we use a dict in the config.py, the one who don't know Python may make some mistakes, such as    comma missing, comma duplicate or quotation missing. 

so I think .ini file may be better.

**Comment by laixintao** [comment]
OK Then we use config.ini : )

**Comment by kingname** [comment]
I have refactored MarkdownPicPicker. Now, it is so easy to write your own uploader.
please pull the newest code and enjoy it.

P.S.: now, I have to write the readme doc. if you have time, you could port MarkdownPicPicker to OS X.
Just add a`OSXImageGrab.py` in `ImageGrab` folder, and write code in `__init__.py` like what I have done there.

**Comment by laixintao** [comment]
Ok  I will follow your work 👍

**Comment by kingname** [comment]
Now, I have finished the OS X support by using pngpaste.
thanks for you help. do you have a reddit accout? I want to release MarkdownPicPicker there, and I will @ you.

**Comment by laixintao** [comment]
cool thanks 👍 
https://www.reddit.com/user/laixintao/
username:laixintao

**Comment by kingname** [comment]
Hi Sir，
Do you have any idea on how to capture image from pasteboard with Python in Mac OS?

**Pull request merged**
