### PR TITLE
support TentcentCOS upload module

### PR DESCRIPTION
**Pull request by Sean10**
Support #17

### CODE REVIEW

**Comment by kingname** [comment]
That is awesome! Brilliant! Excellent! I will check it and merge if everything work fine. 

P.S>: Don't forget to update the Pipfile and Pipfile.lock

**Comment by kingname** [comment]
Thanks for your work. I will check it this weekend.

**Comment by kingname** [comment]
Sir, your code works like a charm. I have already merged it.

But pay attention, I find your codes sometime beyond the rules of PEP8. I will format them in my latter commit(s).

**Comment by Sean10** [comment]
@kingname Sorry for that. Thank you.

**Pull request merged**
